# Generated by Django 2.2.5 on 2019-09-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('status', models.IntegerField(choices=[(0, '実行中'), (1, '完了')], default=0)),
            ],
        ),
    ]
